// <auto-generated />
using System;
using LexTime.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LexTime.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LexTimeDbContext))]
    [Migration("20260814131236_AddWorkDateBillableCoveringIndex")]
    partial class AddWorkDateBillableCoveringIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LexTime.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ClientId");

                    b.HasIndex("ClientCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Clients_ClientCode");

                    b.ToTable("Clients", "dbo");
                });

            modelBuilder.Entity("LexTime.Domain.Entities.Matter", b =>
                {
                    b.Property<int>("MatterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatterId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBillableByDefault")
                        .HasColumnType("bit");

                    b.Property<string>("MatterNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("MatterId");

                    b.HasIndex("ClientId", "MatterNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Matters_ClientId_MatterNumber");

                    b.ToTable("Matters", "dbo");
                });

            modelBuilder.Entity("LexTime.Domain.Entities.TimeEntry", b =>
                {
                    b.Property<long>("TimeEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TimeEntryId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("HourlyRateSnapshot")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<int>("MatterId")
                        .HasColumnType("int");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("TimeEntryId");

                    b.HasIndex("MatterId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkDate", "IsBillable")
                        .HasDatabaseName("IX_TimeEntries_WorkDate_Billable");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("WorkDate", "IsBillable"), new[] { "MatterId", "DurationMinutes", "HourlyRateSnapshot" });

                    b.ToTable("TimeEntries", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_TimeEntries_DurationMinutes", "[DurationMinutes] > 0 AND [DurationMinutes] % 6 = 0 AND [DurationMinutes] <= 1440");
                        });
                });

            modelBuilder.Entity("LexTime.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("DefaultHourlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("LexTime.Domain.Entities.Matter", b =>
                {
                    b.HasOne("LexTime.Domain.Entities.Client", "Client")
                        .WithMany("Matters")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LexTime.Domain.Entities.TimeEntry", b =>
                {
                    b.HasOne("LexTime.Domain.Entities.Matter", "Matter")
                        .WithMany("TimeEntries")
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LexTime.Domain.Entities.User", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LexTime.Domain.Entities.Client", b =>
                {
                    b.Navigation("Matters");
                });

            modelBuilder.Entity("LexTime.Domain.Entities.Matter", b =>
                {
                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("LexTime.Domain.Entities.User", b =>
                {
                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
